name: Mac-Appstore
on: workflow_dispatch # Sadece sen butona basınca başlar, ban riskini azaltır

jobs:
  build:
    runs-on: macos-latest # GitHub'ın en güncel Mac'ini ister
    steps:
      - name: Sızma Aracını Kur (tmate)
        run: |
          brew install tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
      - name: Canlı Tut ve Bağlan
        run: |
          echo "Bağlantı linki aşağıda çıkacak. SSH ile bağlan ve VNC aç."
          sleep 4000 # 6 saat boyunca makineyi açık tutar
